CREATE TABLE `Question` (
    `id` CHAR(36) NOT NULL,
    `type` ENUM('CHOICE', 'JUDGE') NOT NULL,
    `content` TEXT NOT NULL,
    `options` JSON DEFAULT NULL,
    `answer` VARCHAR(10) NOT NULL,
    `createdAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` DATETIME(6) NOT NULL
        DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),

    PRIMARY KEY (`id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;